Attempt to display the translation error in the same step it's run.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -61,13 +61,10 @@ jobs:
         run: yarn test
 
       - name: Check translation files
-        run: yarn gen-translations --fail-on-update
-
-      - name: Display translation error
-        if: ${{ failure() }}
         run: >
-          echo "The translation files seem incomplete. Please run `yarn gen-translations` in the
-          directory root and commit the updated translation files."
+          yarn gen-translations --fail-on-update ||
+          { echo "::error::The translation files seem incomplete. Please run `yarn gen-translations`
+          in the directory root and commit the updated translation files." && exit 1 }
 
   integration-tests:
     runs-on: ubuntu-latest
